### ISSUE TITLE
Confirmation popup doesn't belong to Storage class. It should be extracted in a "view" class.

### ISSUE THREAD

**Issue by abereghici** [sasa-bonta/JavaScript-Cart#1]
https://github.com/sasa-bonta/JavaScript-Cart/blob/ec9a4d8addbaadd70131b2cd3bcf8feb394508f0/resources/js/storage/Storage.js#L30

**Comment by sasa-bonta** [comment]
deleteBtn.addEventListener('click', () => {
                    if (confirm("Delete this item?")) this.action(item)
                });
