### ISSUE TITLE
Please use 'getItem', 'setItem' instead of indexes when you're working with localstorage.

### ISSUE THREAD

**Issue by abereghici** [sasa-bonta/JavaScript-Cart#2]
https://github.com/sasa-bonta/JavaScript-Cart/blob/ec9a4d8addbaadd70131b2cd3bcf8feb394508f0/resources/js/storage/Storage.js#L5

**Comment by sasa-bonta** [comment]
Done
https://github.com/sasa-bonta/JavaScript-Cart/blob/classification/resources/js/storage/Storage.js
